# Generated by Django 5.0.1 on 2024-02-04 06:31

import aerc_website.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Prefer not to say')], default='N', max_length=1)),
                ('age', models.SmallIntegerField(default=18)),
                ('profile', models.ImageField(default='', upload_to=aerc_website.models.profile_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C', 'Crypto'), ('E', 'Stock'), ('R', 'Real Estate'), ('V', 'Vehicle'), ('M', 'Saving'), ('O', 'Other')], default='O', max_length=1)),
                ('current_value', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(default='', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.asset')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(default='', max_length=10)),
                ('lot_width', models.FloatField(default=0)),
                ('lot_depth', models.FloatField(default=0)),
                ('bedroom', models.SmallIntegerField(default=0)),
                ('bathroom', models.SmallIntegerField(default=0)),
                ('parking', models.SmallIntegerField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.SmallIntegerField(default=0)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('dividend', models.FloatField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
                ('market', models.CharField(default='', max_length=10)),
                ('currency', models.CharField(default='', max_length=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2000)),
                ('color', models.CharField(default='Black', max_length=20)),
                ('brand', models.CharField(default='Ford', max_length=20)),
                ('VIN', models.CharField(default='', max_length=30)),
                ('model', models.CharField(default='', max_length=20)),
                ('purchase_price', models.FloatField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.asset')),
            ],
        ),
    ]
