# Generated by Django 5.0.1 on 2024-02-12 22:57
import csv
import os
from django.db import migrations, models


def add_data(apps, schema_editor):
    HousingIndex = apps.get_model('aerc_website', 'HousingIndex')
    with open(os.path.join(os.path.dirname(__file__),'data', 'housing_index.csv'), 'r', encoding='utf-8-sig') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['New housing price indexes'] == 'House only':
                value = 0 if len(row['VALUE']) == 0 else eval(row['VALUE'])
                data = HousingIndex.objects.create(location=row['GEO'], date=f"{row['REF_DATE']}-01", index=value)
                print(f"{data.id:>05} Data inserted: location - {data.location}, time - {data.date}, index - {data.index}")

def remove_data(apps, schema_editor):
    HousingIndex = apps.get_model('aerc_website', 'HousingIndex')
    HousingIndex.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Canada', max_length=50)),
                ('date', models.DateTimeField(default='1980-01-01')),
                ('index', models.FloatField(default=0)),
            ],
        ),
        migrations.RunPython(add_data, remove_data)
    ]
