# Generated by Django 5.0.1 on 2024-02-21 11:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0003_housingindex'),
    ]

    operations = [        
        migrations.AddField(
            model_name='stock',
            name='ticker_symbol',
            field=models.CharField(db_index=True, default='', max_length=5),
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticker_symbol'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('ticker_symbol', 'market')},
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('share', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.stock')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['transaction_date'],
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='symbol',
        ),
    ]
