# Generated by Django 5.0.1 on 2024-02-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aerc_website", "0004_alter_stock_options_alter_vehicle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checksum",
            field=models.CharField(blank=True, max_length=255, verbose_name="checksum"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="checksum",
            field=models.CharField(blank=True, max_length=255, verbose_name="checksum"),
        ),
    ]
