# Generated by Django 5.0.1 on 2024-02-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aerc_website", "0005_user_checksum_vehicle_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="checksum",
            field=models.CharField(blank=True, max_length=255, verbose_name="checksum"),
        ),
        migrations.AddField(
            model_name="house",
            name="checksum",
            field=models.CharField(blank=True, max_length=255, verbose_name="checksum"),
        ),
        migrations.AddField(
            model_name="stock",
            name="checksum",
            field=models.CharField(blank=True, max_length=255, verbose_name="checksum"),
        ),
    ]
