# Generated by Django 5.0.1 on 2024-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0006_crypto_checksum_house_checksum_stock_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(choices=[('CA', 'Canada'), ('AT', 'Atlantic Region'), ('NL', 'Newfoundland and Labrador'), ('SJ', "St. John's, Newfoundland and Labrador"), ('PEI', 'Prince Edward Island'), ('CT', 'Charlottetown, Prince Edward Island'), ('NS', 'Nova Scotia'), ('HF', 'Halifax, Nova Scotia'), ('NB', 'New Brunswick'), ('SJFM', 'Saint John, Fredericton, and Moncton, New Brunswick'), ('QC', 'Quebec'), ('QEC', 'Québec, Quebec'), ('SB', 'Sherbrooke, Quebec'), ('TR', 'Trois-Rivières, Quebec'), ('MTL', 'Montréal, Quebec'), ('OGQ', 'Ottawa-Gatineau, Quebec part, Ontario/Quebec'), ('ON', 'Ontario'), ('OGO', 'Ottawa-Gatineau, Ontario part, Ontario/Quebec'), ('OSW', 'Oshawa, Ontario'), ('TNT', 'Toronto, Ontario'), ('HT', 'Hamilton, Ontario'), ('SC', 'St. Catharines-Niagara, Ontario'), ('KCW', 'Kitchener-Cambridge-Waterloo, Ontario'), ('GH', 'Guelph, Ontario'), ('LD', 'London, Ontario'), ('WS', 'Windsor, Ontario'), ('SY', 'Greater Sudbury, Ontario'), ('PR', 'Prairie Region'), ('MT', 'Manitoba'), ('WP', 'Winnipeg, Manitoba'), ('SA', 'Saskatchewan'), ('RGA', 'Regina, Saskatchewan'), ('SKT', 'Saskatoon, Saskatchewan'), ('ABT', 'Alberta'), ('CGY', 'Calgary, Alberta'), ('ED', 'Edmonton, Alberta'), ('BC', 'British Columbia'), ('KN', 'Kelowna, British Columbia'), ('VNC', 'Vancouver, British Columbia'), ('VCA', 'Victoria, British Columbia')], default='CA', max_length=5),
        ),
    ]
