# Generated by Django 5.0.1 on 2024-02-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0007_locationcategory_house_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='price',
            field=models.FloatField(),
        ),
    ]
