# Generated by Django 5.0.1 on 2024-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0009_house_address_house_postal_code_house_street_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='stock',
            new_name='ticker_symbol',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='purchase_price',
            field=models.FloatField(null=True),
        ),
    ]
