# Generated by Django 5.0.1 on 2024-03-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0010_rename_stock_stocktransaction_ticker_symbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='ticker_symbol',
            new_name='stock',
        ),
    ]
