# Generated by Django 5.0.1 on 2024-03-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0012_alter_stocktransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='price',
        ),
    ]
