# Generated by Django 5.0.1 on 2024-03-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0013_remove_stocktransaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.FloatField(default=0),
        ),
    ]
