# Generated by Django 5.0.1 on 2024-03-13 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0014_asset_purchase_price_alter_asset_current_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('SF', 'Single-family'), ('MF', 'Multi-family'), ('CD', 'Condominium'), ('TH', 'Townhouse'), ('AB', 'Apartment Building'), ('CT', 'Cottage'), ('CO', 'Co-op (Cooperative housing)'), ('CP', 'Commercial Property'), ('IP', 'Industrial Property'), ('RS', 'Retail Space'), ('OB', 'Office Building'), ('WH', 'Warehouse'), ('L', 'Land'), ('F', 'Farm')], default='SF', max_length=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
