# Generated by Django 5.0.1 on 2024-03-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0016_remove_crypto_amount_remove_crypto_coin_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['ticker_symbol'], 'verbose_name': 'Crypto', 'verbose_name_plural': 'Cryptos'},
        ),
        migrations.AddField(
            model_name='crypto',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.FloatField(default=0)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerc_website.crypto')),
            ],
            options={
                'verbose_name': 'Crypto Transaction',
                'verbose_name_plural': 'Crypto Transactions',
                'ordering': ['purchase_date'],
            },
        ),
    ]
