# Generated by Django 5.0.1 on 2024-03-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0018_crypto_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotransaction',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
