# Generated by Django 5.0.1 on 2024-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0019_alter_cryptotransaction_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
