# Generated by Django 5.0.1 on 2024-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aerc_website", "0021_alter_crypto_purchase_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["category"]},
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="VIN",
            field=models.CharField(default="", max_length=30),
        ),
    ]
