# Generated by Django 5.0.1 on 2024-03-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aerc_website", "0022_alter_asset_options_alter_vehicle_vin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField()),
                ("record_value", models.FloatField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aerc_website.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["record_date", "id"],
            },
        ),
    ]
