# Generated by Django 5.0.1 on 2024-03-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0023_assethistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
