# Generated by Django 5.0.1 on 2024-04-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerc_website', '0024_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='share',
            field=models.FloatField(default=0),
        ),
    ]
